trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: Bash@3
  displayName: Terraform Init
  inputs:
    targetType: 'inline'
    script: 'terraform init -input=false'
    workingDirectory: './Terraform/03-modules/'