trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Online(afe07a9d-e6de-4b4c-91eb-3ae7265a9245)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform init'
    workingDirectory: './Terraform/03-modules/'